### PR TITLE
Bump to 3.4.0-15724

### PR DESCRIPTION
**Pull request by francoism90**
- Add permissions to start at boot
- Add background permissions
- Bump version
- Sort flags
- Drop kde.* flags

### CODE REVIEW

**Comment by RayJW** [comment]
Thank you for your contribution! I think we will want to update to the newest version in another commit and then look at all the small incremental improvements separately, what do you think @lil5? Could you maybe also explain some of the additional permissions etc. you added in this PR?

**Comment by lil5** [comment]
To keep testing quality high keep it to this PR, but an explanation on each change is required.

**Comment by francoism90** [comment]
@RayJW @lil5 Thanks for your reply and review. :)

I'm still relatively new to Flatpak, so if anything should be changed/undo, please let me know.

Changes:
- I believe the `--own-name=org.kde.*`, should be removed. It should work with `org.kde.StatusNotifierWatcher`
- I think `--system-talk-name=org.freedesktop.login1` is needed, so the application can track the user. If this is unneeded, I'll remove it.
- `--talk-name=org.gnome.SessionManager`, I think the application use this, but I'm not sure.
- I've fixed the url `$version` - `$version4`, unless the 4 has a meaning?
- And I've sorted the flags

**Comment by RayJW** [comment]
> I believe the `--own-name=org.kde.*`, should be removed. It should work with `org.kde.StatusNotifierWatcher`
That checks out. We actually wanted to make that change already, but we don't get around to testing a lot, since neither of us actually needs this software as far as I am aware. Did you test if the tray icon still properly works after that change?

> * I think `--system-talk-name=org.freedesktop.login1` is needed, so the application can track the user. If this is unneeded, I'll remove it.
Track in what way? The only use case I saw for this permission so far is to enable start on login functionality, does the client provide that functionality and does it work with this permission enabled?

> * `--talk-name=org.gnome.SessionManager`, I think the application use this, but I'm not sure.
Use for what exactly? I think so far it worked great without, or is there a function that was broken for you without it? It's a possibility for sure since the only tests we can do is by hand, so not all functionality is tested as thorough!

> * I've fixed the url `$version` - `$version4`, unless the 4 has a meaning?
The 4 does indeed have a meaning, it's for the fourth part of the version regex, since the URL doesn't contain the whole version identifier. However, it was broken due to another issue, which I fixed upstream. This should work again, once you rebase with main :)

**Comment by francoism90** [comment]
@RayJW Thanks for your review again, and the explanation about the flags. :)

I'see other PRs are open already, also on for bumping this package.
Should I close this one? :)

**Comment by RayJW** [comment]
No, I think we keep your version. The other PR is just automatically made by the bot. If you can confirm that the new flags enable new functionality according to your intention and remove all the unneeded changes, I think we can merge this. Agreed, @lil5?

**Comment by francoism90** [comment]
@RayJW Maybe the flags aren't needed.

If you would like me to remove some, please let me know. :)

**Comment by RayJW** [comment]
So, I just tested your build and for me personally neither start on boot seemed to work nor did the background portal seem to change anything since it seems to work fine. Also the tray icon doesn't work anymore with the removed permissions so that doesn't seem to work out either.

Were those things working on your end when you tested those changes? It could still be a my machine(tm) issue.

**Comment by francoism90** [comment]
@RayJW Thanks for testing. :)

I'll close this PR, as it's incomplete, and I think the other PRs are better.

**Pull request closed without merging**
