### PR TITLE
Drop org.kde.* own-name

### PR DESCRIPTION
**Pull request by bbhtt**
This is no longer required with any supported runtimes

https://docs.flatpak.org/en/latest/desktop-integration.html#statusnotifier

> Most implementations of StatusNotifer have dropped this requirement

https://github.com/flathub/flatpak-builder-lint/issues/ 66#issuecomment-1386033025

### CODE REVIEW

**Comment by lil5** [comment]
I remember keeping it in there just in case as testing each option takes lots of time, I’ll give it a go sometime this weekend/ next week

**Comment by bbhtt** [comment]
> I remember keeping it in there just in case as testing each option takes lots of time, I’ll give it a go sometime this weekend/ next week

This will now be blocked through the linter https://docs.flathub.org/docs/for-app-authors/linter. Did you get a chance?

**Comment by faeb5** [comment]
I test this today, unfortunately it does not seem to work. No status icon for me, which seems to be confirmed by this exception: `failed to register service "org.kde.StatusNotifierItem-7-1"`

**Comment by lil5** [comment]
@faeb5 Thanks for the comment

Could attempt org.kde.StatusNotifierItem-$PID-$ITEM_ID this should satisfy the new linter rules too.

**Comment by bbhtt** [comment]
Exceptions in case of legacy tray usage are accepted see https://docs.flathub.org/docs/for-app-authors/linter/#finish-args-wildcard-name-own-name

The process is explained at the bottom of the page.

**Comment by bbhtt** [comment]
> Exceptions in case of legacy tray usage are accepted see https://docs.flathub.org/docs/for-app-authors/linter/#finish-args-wildcard-name-own-name
> 
> The process is explained at the bottom of the page.

> Could attempt --talk=org.kde.StatusNotifierItem-$PID-$ITEM_ID this should satisfy the new linter rules too.

That won't work.

**Comment by faeb5** [comment]
Thanks @bbhtt , I created a MR over at flathub-infra/flatpak-builder-lint#283 which adds the exception for the Synology Client.

**Comment by lil5** [comment]
@faeb5 So if i understand correctly I can close this Under wontfix correct?

**Pull request closed without merging**
