### PR TITLE
Update to 3.1.0-12923

### PR DESCRIPTION
**Pull request by RayJW**
Updates the deb package to the new 3.1.0-12923 version, released on 2022-04-06.

### CODE REVIEW

**Comment by RayJW** [comment]
Closes #22

**Comment by jibsaramnim** [comment]
@RayJW it seems like the screenshot originally used has been re-saved by the Synology folk into a webp variant [here](https://www.synology.com/img/dsm/drive/seamlessly_01.webp). The original has been removed, which is what's causing the build to fail. 

I was going to make a PR myself but I realized you had already done this. If you have a moment, perhaps you can change this in line 17 of `com.synology.SynologyDrive.metainfo.xml`?

**Comment by RayJW** [comment]
@jibsaramnim I updated my PR with a new commit containing the fix for the new image link. Lmk if there is anything else to do before merging :)

**Comment by jibsaramnim** [comment]
>  I updated my PR with a new commit containing the fix for the new image link.

Welp, it still failed. Perhaps Flathub doesn't like webp images? I'm not sure.. we might have to wait for/ping someone in the know -- I'm only a (tiny) contributor myself. Thank you kindly for giving this a try though!

**Comment by jibsaramnim** [comment]
Ah yes, `webp` does not seem to be supported. I found this in the build logs of the failed build:

> Failed to download https://www.synology.com/img/dsm/drive/seamlessly_01.webp: Couldn’t recognize the image file format for file “/srv/buildbot/worker/build-x86_64-7/build/.flatpak-builder/screenshots-cache/com.synology.SynologyDrive-seamlessly_01.webp”

I.. am not sure if there are built-in methods of converting something on the fly, or if we have to try to find an alternative host/source of a jpeg image instead. Hopefully someone in the know will be able to chime in on how to deal with this. 

This is also what's preventing #25, so finding a fix for those should hopefully fix both PRs, which would be very nice indeed :).

**Comment by RayJW** [comment]
@jibsaramnim Thanks for investigating this. It's really weird because I couldn't find any other documentation or errors regarding webp images. Considering this codec is gaining quite some traction, I find it odd that no one else seems to have walked into this issue yet, but who knows.
Closing both PRs would indeed be nice, as especially #25 is important because it might be an alarming error to users, and it's also just bad practice.

**Comment by jibsaramnim** [comment]
@hfiguiere Hi :wave:! you've helped me earlier this year with a version bump back then. I hope it's alright I'm tagging you directly; do you happen to know any way we might be able to get the screenshot download bit figured out so these two PRs can be approved and merged? It'd be especially great to get rid of the (admittedly rather ominous sounding) warning shown to all users regarding org.freedesktop.Sdk.

**Comment by hfiguiere** [comment]
webp isn't supported.

**Comment by jibsaramnim** [comment]
> webp isn't supported.

Is it possible to include a jpeg screenshot directly in this repository and use that?

**Comment by cstamas** [comment]
Seems jpg exists also https://www.synology.com/img/dsm/drive/seamlessly_01.jpg

**Comment by RayJW** [comment]
> Seems jpg exists also [synology.com/img/dsm/drive/seamlessly_01.jpg](https://www.synology.com/img/dsm/drive/seamlessly_01.jpg)

Amazing, this seems to finally do the trick. Thank you for finding this @cstamas. I think we should now go ahead with merging this and #25 if possible to get this Flatpak up-to-date again @jibsaramnim.

**Review by jibsaramnim — APPROVED** [review]
Tested and confirmed working on my system running Fedora 36 (GNOME). Thanks so much for making these changes! (Note that you'll have to pull in the latest from master once this PR is merged or apply the same fix in #25 for that one to be able to successfully build, too)

(I'm only a small contributor myself, so I can't merge this for you. But I hope my $0.02 are helpful here :)).

**Comment by RayJW** [comment]
> Tested and confirmed working on my system running Fedora 36 (GNOME). Thanks so much for making these changes!
> 
> image
> 
> Note that you'll have to pull in the latest from master once this PR is merged or apply the same fix in #25 for that one to be able to successfully build, too.
> 
> (I'm only a small contributor myself, so I can't merge this for you. But I hope my $0.02 are helpful here :)).

Perfect, thank you for testing! It also seems to work without issues on my system so far.

I will rebase #25 with main once this one is merged because I wanted to make them separate PRs to avoid any confusion or blockers with one or the other :)

**Comment by jibsaramnim** [comment]
Hi @hfiguiere! OP has fixed the webp reference and everything seems to be building and working great now. It would be really nice if this one could be merged so that #25 can be merged as-well (it's held up by the same image issue that's already fixed in this PR). Would you be able to help get these merged for us?

**Comment by hfiguiere** [comment]
build failed. :-(

**Pull request merged**
