### PR TITLE
update to 3.2.1

### PR DESCRIPTION
**Pull request by lil5**
- Updates to version v3.2.1 (deprecating #28)
- Re-add tray icon support (cherry picked from #29)

### CODE REVIEW

**Comment by lil5** [comment]
```log
Performing POST request to https://hub.flathub.org/api/v1/build
An exception occurred while performing the request: HTTPSConnectionPool(host='hub.flathub.org', port=443): Max retries exceeded with url: /api/v1/build (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9a8e148be0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

Is this rate limiting? Or do I need to ask someone from flathub?

**Comment by lil5** [comment]
@RayJW I've added your commit to this one

**Comment by lil5** [comment]
```log
➜  ~ flatpak install https://dl.flathub.org/build-repo/12829/com.synology.SynologyDrive.flatpakref
error: Can't load uri https://dl.flathub.org/build-repo/12829/com.synology.SynologyDrive.flatpakref: Server returned status 404
```

@hfiguiere I guess I was too late to test this.

I built this locally and it worked fine; For my perspective this PR is ready to be merged but if you have reservations I'm open for critic.

**Comment by lil5** [comment]
@RayJW For such small changes I thought no harm done, lets just get it working, for larger PR's I'd agree with you. But it's a matter of style as well :shrug: 

@hfiguiere +1 for getting RayJW on the maintainers list.

**Comment by RayJW** [comment]
No, I totally agree, no harm done. I just wanted to let you know in case you were not aware of it ^^

Again, thank you for your help :)

**Review by RayJW — APPROVED** [review]
Everything looks good to me. Let's merge it.

**Pull request merged**
